extends:
  - stylelint-config-recommended-scss
  - stylelint-config-rational-order
  - stylelint-prettier/recommended

plugins:
  - stylelint-order
  - stylelint-prettier
  - stylelint-scss

ignoreFiles:
  - "./src/styles/*.**.css"

rules:
  prettier/prettier: true
  no-descending-specificity: null
  plugin/rational-order:
    - true
    - empty-line-between-groups: true
